engines:
  duplication:
    enabled: true
    exclude_paths:
    - "sample"
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- "test"
- "**/__mocks__"
- "**/*.spec.js"
- "**/*.spec.jsx"
