logFilters:
  - code: YN0076
    level: discard

nodeLinker: node-modules

plugins:
  - checksum: 9b6f8a34bda80f025c0b223fa80836f5e931cf5c8dd83e10ccfa9e677856cf1508b063d027060f74e3ce66ee1c8a936542e85db18a30584f9b88a50379b3f514
    path: .yarn/plugins/@yarnpkg/plugin-nolyfill.cjs
    spec: "https://raw.githubusercontent.com/wojtekmaj/yarn-plugin-nolyfill/v1.0.1/bundles/@yarnpkg/plugin-nolyfill.js"
