logFilters:
  - code: YN0076
    level: discard

nodeLinker: node-modules

plugins:
  - checksum: 24a2171abe511205f3184779105076031ca8daefb3fecb744e3d4f3f4010785881127bfc2d73445f7f101bf200d4a5931ec75feb543e50ffbf584da53a2f62cf
    path: .yarn/plugins/@yarnpkg/plugin-nolyfill.cjs
    spec: 'https://raw.githubusercontent.com/wojtekmaj/yarn-plugin-nolyfill/v0.1.3/bundles/@yarnpkg/plugin-nolyfill.js'
